sudo: required
services:
    - docker

before_install:
    - docker build -t $DOCKER_ID/client-test -f ./client/Dockerfile.dev ./client
    - docker build -t $DOCKER_ID/api-test -f ./api/Dockerfile.dev ./api

    # Install eksctl
    -  curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp \
       sudo mv /tmp/eksctl /usr/local/bin

scripts:
    - docker run -e CI=true $DOCKER_ID/client-test npm run test
    - docker run -e CI=true $DOCKER_ID/api-test npm run test

after_success:
    - docker build -t $DOCKER_ID/client ./client
    - docker build -t $DOCKER_ID/api    ./api
    - docker build -t $DOCKER_ID/nginx  ./nginx
    - echo $DOCKER_PW | docker login -u $DOCKER_ID --password-stdin
    - docker push $DOCKER_ID/client
    - docker push $DOCKER_ID/api
    - docker push $DOCKER_ID/nginx


    