sudo: required
services:
    - docker

before_install:
    - docker build -t $DOCKER_ID/client-test -f ./client/Dockerfile.dev ./client
    - docker build -t $DOCKER_ID/api-test -f ./api/Dockerfile.dev ./api

scripts:
    - docker run -e CI=true $DOCKER_ID/client-test npm run test
    - docker run -e CI=true $DOCKER_ID/api-test npm run test
    