sudo: required
services:
    - docker
# env:
#     global:
#         - SHA=$(git rev-parse HEAD)
#         - CLOUDSDK_CORE_DISABLE_PROMPTS=1

install:
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - sudo mv ./kubectl /usr/local/bin/kubectl
    - mkdir ${HOME}/.kube
    # - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
    - sed -i 's/KUBE_CLUSTER_NAME/'"$KUBE_CLUSTER_NAME"'/g' config
    - sed -i 's/KUBE_CLUSTER_CERTIFICATE/'"$KUBE_CLUSTER_CERTIFICATE"'/g' config
    - sed -i 's/KUBE_CLIENT_CERTIFICATE/'"$KUBE_CLIENT_CERTIFICATE"'/g' config
    - sed -i 's/KUBE_CLIENT_KEY/'"$KUBE_CLIENT_KEY"'/g' config
    - sed -i 's/KUBE_ADMIN_PWD/'"$KUBE_ADMIN_PWD"'/g' config
    - kubectl config use-context $KUBE_CLUSTER_NAME
    - cd $TRAVIS_BUILD_DIR
    # - docker build -t $DOCKER_ID/client-test -f ./client/Dockerfile.dev ./client
    # - docker build -t $DOCKER_ID/api-test -f ./api/Dockerfile.dev ./api

scripts:
    - kubectl get pods
    # - docker run -e CI=true $DOCKER_ID/client-test npm run test
    # - docker run -e CI=true $DOCKER_ID/api-test npm run test

# deploy:
#     provider: script
#     script: bash ./deploy.sh
#     on:
#         branch: master


