version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  create-deployment:
    executor: aws-eks/python3
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          aws-profile: terraform
          aws-region: us-east-1
          cluster-name: my-eks
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: /k8s
          get-rollout-status: true
          show-kubectl-command: true

workflows:
  deployment:
    jobs:
      - create-deployment