jobs:
  build:
    steps:
      - checkout

      - run: docker build -t lcymburajr/client-test -f ./client/Dockerfile.dev ./client
      
      - run: docker run lcymburajr/client-test npm run test

      - setup_remote_docker:
        version: 19.03.13
           