version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run: docker build -t $DOCKER_USER/client-test -f ./client/Dockerfile.dev ./client
  test:
    steps:
      - checkout
      - run: docker run -e CI=true $DOCKER_USER/client-test npm run test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build