jobs:
 test:
   machine: true
   steps:
     - checkout
     # login to docker
     - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     # build the test image
     - run: docker build -t $DOCKER_USER/client-test -f ./client/Dockerfile.dev ./client
     # test the image
     - run: docker run -e CI=true $DOCKER_USER/client-test npm run test
           